---
title: "Sources"
format: html
---

## Explanation of Sources

Reconstructing the lives of Chinese soldiers who served during the American Civil War required careful and intentional work across many different historical records. Unlike famous, well-documented generals and leaders, many of these men appear only briefly in the historical archive, and oftentimes with only their name. As clerks were unfamiliar with Chinese names, they could also be in several different records under different names. Their stories exist in scattered documents created by the military, the government, newspapers, and later researchers and archivists. This project attempts to piece those fragments together.

Using military records, personal memoirs, and newspaper archives, this study attempts to reconstruct the experiences of Chinese soldiers and analyze their role in shaping military and racial policies. Sources such as military and government records (enlistment records, military reports, war correspondence and pension records) provide insight on identification and enrollment numbers and can be found in the National Archives and the U.S. War Department Reports as well as Fold3– a database made for searching for soldier records. Further, 19th-century newspapers, propaganda and recruitment materials, and documents describing political debates over the inclusion of Asian soldiers will provide a useful insight to track contemporary attitudes toward Asian military service.

Many soldiers in this project survive only in a single document like a muster roll, but leave no trace in later records. When working with marginalized communities, this archival silence is not unusual. Historical records often preserve the lives of some people more clearly than others. Language barriers, racial prejudice, poverty, and mobility made it more difficult, especially in this era, for Chinese migrants to appear consistently in official records. This project embraces those gaps, as even brief traces in the archive reveal that Chinese soldiers were participating in the Civil War. The list, and the information within, will continue to grow as new documents are discovered and cataloged. If you have additional information about any individuals featured in this project, please consider contacting the researcher. History is always a work in progress.

Other Readings
